### PR TITLE
Update Kalman.h

### PR DESCRIPTION
**Pull request by hehao9051**
because P[1][0] = P[0][1],so i suggest to simplify the code;

### CODE REVIEW

**Comment by hehao9051** [comment]
because P[1][0] = P[0][1],so i suggest to simplify the code;

**Comment by Lauszus** [comment]
Sorry, but this is incorrect. ```P[1][0] != P[0][1]```. Just take a look at these lines: https://github.com/TKJElectronics/KalmanFilter/blob/master/Kalman.h#L79-L80 where two different terms are subtracted from the two values.

**Comment by Lauszus** [comment]
Or just print the two values and you will see that they are different.

**Comment by hehao9051** [comment]
No,they are same,because P is a  symmetric matrix;P01 = ,P10 =‍‍‍‍
according P01=P10;If you calculate it use the method in your blog,you will find they are same actually.‍See the attachment.‍‍






------------------ 原始邮件 ------------------
发件人: "Kristian Sloth Lauszus";<notifications@github.com>;
发送时间: 2015年1月15日(星期四) 晚上8:50
收件人: "TKJElectronics/KalmanFilter"<KalmanFilter@noreply.github.com>; 
抄送: "浩"<571532760@qq.com>; 
主题: Re: [KalmanFilter] Update Kalman.h (#3)




Sorry, but this is incorrect. P[1][0] != P[0][1]. Just take a look at these lines: https://github.com/TKJElectronics/KalmanFilter/blob/master/Kalman.h#L79-L80 where two different terms are subtracted from the two values.

**Comment by hehao9051** [comment]
No,they are same,because P is a  symmetric matrix;Please see the mail i send to you.

**Pull request closed without merging**
