### PR TITLE
Update to new C++ standards

### PR DESCRIPTION
**Pull request by ThePyProgrammer**

### CODE REVIEW

**Comment by mindThomas** [comment]
Thank you for your contribution.
Please do not commit your IDE project directory (.idea) and do not commit the build directory (cmake-build-debug)

**Comment by ThePyProgrammer** [comment]
I have updated the branch by removing these files. I apologise for the inconvenience caused.

**Comment by ThePyProgrammer** [comment]
Hi, I apologise for over-commenting but is there anything else that I should change? For example, are there any modifications? I hope you will look into my inquiry. Thank you.

**Comment by Lauszus** [comment]
To be honest I'm not a big fan of these changes. To be it doesn't really add anything in my opinion.

Also it will break compatibility with older versions of the Arduino IDE, which uses an older version of the GCC compiler.

**Comment by Lauszus** [comment]
To be honest I'm not a big fan of these changes. To me it doesn't really add anything. It's simply just cosmetic change, which I think makes the code harder to read.

Also it will break compatibility with older versions of the Arduino IDE, which uses an older version of the GCC compiler.

**Comment by ThePyProgrammer** [comment]
Ok, noted. I mean based on all I've learned, the suggestion is always to represent a C++ Function as
`auto function_name(params) -> return type`
Write your function trailing return type, at least that's what I've heard. Although this has only been allowed since C++ 14, so I get your point.
But thank you for considering my code, I apologise for any inconvenience caused. Thank you.

**Comment by Lauszus** [comment]
> Ok, noted. I mean based on all I've learned, the suggestion is always to represent a C++ Function as ```auto function_name(params) -> return type```

Yeah might be true if using C++ 14, but I can't see how `auto setAngle(float angle) -> void` is easier to read and understand than just `void setAngle(float angle)` and I doubt that it makes any difference for the compiler.

> But thank you for considering my code, I apologise for any inconvenience caused. Thank you.

No problem. Thanks for submitting the PR anyway.

**Comment by mindThomas** [comment]
Thank you @Lauszus. You beat me on the answer.
I completely agree. This PR is more about aesthetics. The trailing return types makes absolutely no difference in our usecase. Where it starts to make a lot of difference is when you use templates where the return type is deduced from the templatization.

But thank you @ThePyProgrammer for raising the awareness.

**Pull request closed without merging**
