### PR TITLE
Working in the 32bits mcu

### PR DESCRIPTION
**Pull request by gabrielSa**
I changed the code like you suggested

### CODE REVIEW

**Comment by Lauszus** [comment]
Have you tested it to confirm that it is working?

**Comment by gabrielSa** [comment]
Yes, in my nodeMCU(esp8266) worked fine 
 
  Em qua, 1 fev, 2017 às 12:39, Kristian Sloth Lauszus&It;notifications@github.com> escreveu:   
Have you tested it to confirm that it is working?

**Comment by Bomanaziba** [comment]
hi, guys I tried working with Kalman filter library and I had an error 

Below are details

Arduino: 1.8.1 (Windows 10), Board: "Intel® Galileo"

In file included from C:\Users\OGONI\Documents\Arduino\MPU6050\MPU6050.ino:41:0:

C:\Users\OGONI\AppData\Local\Arduino15\packages\Intel\hardware\i586\1.6.7+1.0\libraries\Wire\src/Wire.h: In function 'void setup()':

C:\Users\OGONI\AppData\Local\Arduino15\packages\Intel\hardware\i586\1.6.7+1.0\libraries\Wire\src/Wire.h:90:39: error: local class 'class setup()::TwoWire' shall not have static data member 'const uint32_t setup()::TwoWire::RECV_TIMEOUT' [-fpermissive]

C:\Users\OGONI\AppData\Local\Arduino15\packages\Intel\hardware\i586\1.6.7+1.0\libraries\Wire\src/Wire.h:91:39: error: local class 'class setup()::TwoWire' shall not have static data member 'const uint32_t setup()::TwoWire::XMIT_TIMEOUT' [-fpermissive]

MPU6050:45: error: 'class setup()::TwoWire' has no member named 'setClock'

C:\Users\OGONI\Documents\Arduino\MPU6050\I2C.ino: In function 'uint8_t i2cWrite(uint8_t, uint8_t*, uint8_t, bool)':

I2C:26: error: 'Wire' was not declared in this scope

C:\Users\OGONI\Documents\Arduino\MPU6050\I2C.ino: In function 'uint8_t i2cRead(uint8_t, uint8_t*, uint8_t)':

I2C:39: error: 'Wire' was not declared in this scope

Multiple libraries were found for "Wire.h"
 Used: C:\Users\OGONI\AppData\Local\Arduino15\packages\Intel\hardware\i586\1.6.7+1.0\libraries\Wire
 Not used: C:\Users\OGONI\AppData\Local\Arduino15\packages\Intel\hardware\i586\1.6.7+1.0\libraries\Servo
exit status 1
'class setup()::TwoWire' has no member named 'setClock'

I'll be grateful for any solution, its of dire importance
thank you

**Comment by Lauszus** [comment]
@gabrielSa thank you!

**Comment by Lauszus** [comment]
@Bomanaziba please install the library via the Arduino library manager: https://www.arduino.cc/en/Guide/Libraries.

**Pull request merged**
